Update numpy and scikit package versions
The current version was causing Heroku to fail with the error
`ImportError: cannot import name '_validate_lengths'`.